import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

import Navbar from "@/app/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} suppressHydrationWarning>
        <Navbar />
        <main className="prose p-12 text-ce">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}

// const Navbar = () => {
//   return (
// <div className="navbar bg-base-100">
//   <div className="flex-1">
//     <Link href="/" className="btn btn-ghost text-xl">
//       🔥 Stripe for SaaS
//     </Link>
//   </div>
//   <div className="flex-none">
//     <ul className="menu menu-horizontal px-1">
//       <li>
//         <Link href="/" className="btn">
//           Home
//         </Link>
//       </li>
//       <li>
//         <Link href="/photos" className="btn mx-3">
//           Photos
//         </Link>
//       </li>
//       <li>
//         <Link href="/user" className="btn">
//           User Auth
//         </Link>
//       </li>
//     </ul>
//   </div>
// </div>
//     <div className="navbar bg-white/90 backdrop-blur-md shadow-lg px-8 py-4 sticky top-0 z-50">
//       <div className="flex-1 items-center flex gap-3">
//         {/* Logo + Brand Name */}
//         <Link
//           href="/"
//           className="flex items-center gap-2 text-3xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-purple-500 via-pink-500 to-red-500 hover:scale-105 transition-transform duration-300"
//         >
//           <span>🔥</span>
//           <span>Stripe for SaaS</span>
//         </Link>

//         {/* Optional Tagline */}
//         <span className="text-sm text-gray-500 hidden md:inline">
//           Your modern SaaS payment platform
//         </span>
//       </div>

//       <div className="flex-none">
//         <ul className="menu menu-horizontal px-1 gap-3">
//           <li>
//             <Link
//               href="/"
//               className="px-4 py-2 rounded-xl font-medium text-gray-700 hover:text-white hover:bg-gradient-to-r from-purple-500 via-pink-500 to-red-500 transition-all duration-300"
//             >
//               Home
//             </Link>
//           </li>
//           <li>
//             <Link
//               href="/photos"
//               className="px-4 py-2 rounded-xl font-medium text-gray-700 hover:text-white hover:bg-gradient-to-r from-purple-500 via-pink-500 to-red-500 transition-all duration-300"
//             >
//               Photos
//             </Link>
//           </li>
//           <li>
//             <Link
//               href="/user"
//               className="px-4 py-2 rounded-xl font-medium text-gray-700 hover:text-white hover:bg-gradient-to-r from-purple-500 via-pink-500 to-red-500 transition-all duration-300"
//             >
//               User Auth
//             </Link>
//           </li>
//         </ul>
//       </div>
//     </div>
//   );
// };
